#!/bin/sh
hostname=$(uname -n)
distro=$(lsb_release -d | awk -F: '{ print $2 }')
kernel=$(uname -r)
memused=$(free -m | awk 'NR==2{ printf "%s MB in use", $3 }')
uptime=$(uptime -p)
cpu=$(top -b -n1 | grep Cpu | awk '{ print $2 }')

echo
echo -e "\e[33m\e[1m HOSTNAME:\e[0m\t\e[1m$hostname\e[0m"
echo -e "\e[33m\e[1m DISTRO: \e[0m$distro"
echo -e "\e[33m\e[1m KERNEL: \e[0m\t$kernel"
echo -e "\e[33m\e[1m UPTIME: \e[0m\t$uptime"
echo ___________________________________________________
echo
echo -e "\e[31m\e[1m \e[4mCPU:\e[0m"
echo $cpu %
echo -e "\e[31m\e[1m \e[4mMEMORY:\e[0m"
echo $memused
echo
echo -e "\e[31m\e[1m \e[4mDISK SPACE:\e[0m"
df -ht ext4
echo
echo -e "\e[31m\e[1m \e[4mCORE TEMPS:\e[0m"
sensors -A

echo -e "\e[31m\e[1m \e[4mDRIVE TEMPS:\e[0m"
hddtemp /dev/sd?

