#!/bin/sh

# Set session variables
export PATH=$PATH:$HOME/.local/bin
export EDITOR="nvim"
export TERMINAL="st"

# Start the gnome-keyring
#dbus-update-activation-environment --systemd DISPLAY
#eval $(/usr/bin/gnome-keyring/daemon --start --components=pkcs11,secrets,ssh)
#export SSH_AUTH_SOCK

# Start misc processes
exec picom -bC &
$HOME/.fehbg &
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec dunst &
exec xautolock -time 10 -locker "xset dpms force off" &
#exec xscreensaver -no-splash &

# Start DWM
exec dwmblocks &
exec dwm

