#!/bin/sh

DEST=$HOME/Documents/Linux/home

# *** COPY CONFIG FOLDER ***

# DWM Environment
if [ -f $HOME/.config/dwm/config.h ]; then
    suckless=("dwm" "st" "dwmblocks" "dmenu")
    for s in ${suckless[@]}; do
        rsync -av --progress $HOME/.config/$s $DEST/.config
    done
fi

# BSPWM
if [ -d $HOME/.config/bspwm ]; then
    bspwm=("bspwm" "sxhkd" "polybar")
    for b in ${bspwm[@]}; do
        rsync -av --progress $HOME/.config/$b $DEST/.config
    done
fi

# General configs
configs=("nvim" "sxiv" "ranger" "dunst" "termite")
for c in ${configs[@]}; do
    rsync -av --progress --delete $HOME/.config/$c $DEST/.config
done

# *** COPY LOCAL FOLDERS ***
rsync -av --progress --delete $HOME/.local/bin $DEST/.local
rsync -av --progress --delete $HOME/.local/share/fonts $DEST/.local/share

# *** COPY DOT FILES ***
cp -v $HOME/.bashrc $DEST

