#!/bin/bash

while true
do
    read -p " Display the date? (y/n)" answer

    case $answer in 
        [yY]* ) printf $(date +'%F')
            break;;

        [nN]* ) exit;;

        * ) echo " Please answer y or n.";;
    esac
done


