#!/bin/bash

if [ $(pamixer --get-mute) = true ];then
    echo 🔇 
    notify-send "Muted" -u low -i audio-volume-muted-symbolic
    exit
fi

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
    icon="🔊 "
elif [ "$vol" -lt "30" ]; then
    icon="🔈 "
else
    icon="🔉 "
fi

echo "$icon$vol%"
